[package]
name = "turn-store"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.9.0", features = ["postgres", "runtime-tokio", "macros", "migrate", "uuid", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.12", features = ["serde"] }
anyhow = "1"
async-stream = "0.3"
eventsource-stream = "0.2"
futures-util = "0.3"
redis = {version="1",features=["connection-manager","tokio-comp","streams"]}
reqwest = { version = "0.12", features = ["json", "stream", "rustls-tls"] }
